# Generated by Django 4.2.17 on 2025-02-19 05:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("childapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name_plural": "Children",
            },
        ),
        migrations.RemoveField(
            model_name="child",
            name="name",
        ),
        migrations.AddField(
            model_name="child",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="child",
            name="assigned_health_professional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_professional_children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="assigned_trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainer_children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="emergency_contact",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="emergency_phone",
            field=models.CharField(
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="grade_level",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="child",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="medical_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="child",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="child_photos/"),
        ),
        migrations.AddField(
            model_name="child",
            name="registration_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="school_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="child",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="guardian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardian_children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="hobbies",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="interests",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="place",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
