# Generated by Django 4.2.17 on 2025-02-19 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("childapp", "0002_alter_child_options_remove_child_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name_plural": "Children"},
        ),
        migrations.RemoveField(
            model_name="child",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="child",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="child",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
