# Generated by Django 4.2.17 on 2025-02-19 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("childapp", "0004_remove_child_emergency_phone_alter_child_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
