# Generated by Django 4.2.17 on 2025-02-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0003_remove_guardian_email_remove_guardian_fname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("specialization", models.CharField(max_length=255)),
                ("date_joined", models.DateField(auto_now_add=True)),
                ("certification", models.TextField(blank=True, null=True)),
                ("experience", models.IntegerField()),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="img/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
