# Generated by Django 4.2.17 on 2025-02-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_trainer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Trainer",
        ),
    ]
