# Generated by Django 4.2.17 on 2025-02-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_delete_trainer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Guardian",
        ),
    ]
