# Generated by Django 4.2.17 on 2025-02-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainerapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="trainer",
            name="specialization",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
